package vista;

/**
 *
 * @author MiguelAngel
 */
public class JFrmPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        this.jlblImageFreezer.setVisible(false);
        this.jlblImageWasher.setVisible(false);
        this.jlblImagePants.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        jpMenu = new javax.swing.JPanel();
        panelAgregar = new javax.swing.JPanel();
        jPushAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpushEliminar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpushListar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpParent = new javax.swing.JPanel();
        jpAgregar = new javax.swing.JPanel();
        jlblMsj1_Agregar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtfCodigo_Agregar = new javax.swing.JTextField();
        jtfPrecio_Agregar = new javax.swing.JTextField();
        jtfStock_Agregar = new javax.swing.JTextField();
        jtfMarca_Agregar = new javax.swing.JTextField();
        jtfPies_Agregar = new javax.swing.JTextField();
        jcbCarga_Agregar = new javax.swing.JComboBox<>();
        jcbTipo_Agregar = new javax.swing.JComboBox<>();
        jrbMasculino_Agregar = new javax.swing.JRadioButton();
        jrbFemenino_Agregar = new javax.swing.JRadioButton();
        jbtnAgregar_Agregar = new javax.swing.JButton();
        jbtnReset_Agregar = new javax.swing.JButton();
        jlblCodigo_Agregar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbProducto = new javax.swing.JComboBox<>();
        jlblMsj2_Agregar = new javax.swing.JLabel();
        jlblImagePants = new javax.swing.JLabel();
        jlblImageWasher = new javax.swing.JLabel();
        jlblImageFreezer = new javax.swing.JLabel();
        jpEliminar = new javax.swing.JPanel();
        jlblEliminarProducto = new javax.swing.JLabel();
        jtfBuscar_Eliminar = new javax.swing.JTextField();
        jbtnEliminar_Eliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jlblNoExiste_Eliminar = new javax.swing.JLabel();
        jpListar = new javax.swing.JPanel();
        jlblListar_Listar = new javax.swing.JLabel();
        jbtnListar_Listar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaListar = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jMenuProcesos = new javax.swing.JMenu();
        jmiAgregar = new javax.swing.JMenuItem();
        jmiEliminar = new javax.swing.JMenuItem();
        jmiListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPushAgregar.setBackground(new java.awt.Color(234, 234, 234));
        jPushAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPushAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPushAgregarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Add_Database_16px.png"))); // NOI18N
        jLabel1.setText("   Agregar");

        javax.swing.GroupLayout jPushAgregarLayout = new javax.swing.GroupLayout(jPushAgregar);
        jPushAgregar.setLayout(jPushAgregarLayout);
        jPushAgregarLayout.setHorizontalGroup(
            jPushAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPushAgregarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPushAgregarLayout.setVerticalGroup(
            jPushAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPushAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpushEliminar.setBackground(new java.awt.Color(234, 234, 234));
        jpushEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpushEliminar.setPreferredSize(new java.awt.Dimension(180, 60));
        jpushEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpushEliminarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Trash_Can_16px.png"))); // NOI18N
        jLabel2.setText("   Eliminar");

        javax.swing.GroupLayout jpushEliminarLayout = new javax.swing.GroupLayout(jpushEliminar);
        jpushEliminar.setLayout(jpushEliminarLayout);
        jpushEliminarLayout.setHorizontalGroup(
            jpushEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpushEliminarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpushEliminarLayout.setVerticalGroup(
            jpushEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpushEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpushListar.setBackground(new java.awt.Color(234, 234, 234));
        jpushListar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpushListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpushListarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_List_View_16px.png"))); // NOI18N
        jLabel3.setText("   Listar");

        javax.swing.GroupLayout jpushListarLayout = new javax.swing.GroupLayout(jpushListar);
        jpushListar.setLayout(jpushListarLayout);
        jpushListarLayout.setHorizontalGroup(
            jpushListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpushListarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpushListarLayout.setVerticalGroup(
            jpushListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpushListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAgregarLayout = new javax.swing.GroupLayout(panelAgregar);
        panelAgregar.setLayout(panelAgregarLayout);
        panelAgregarLayout.setHorizontalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpushEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jPushAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpushListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelAgregarLayout.setVerticalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPushAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpushEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpushListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jpMenu.add(panelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 170, 410));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpParent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpParent.setPreferredSize(new java.awt.Dimension(665, 410));
        jpParent.setLayout(new java.awt.CardLayout());

        jpAgregar.setPreferredSize(new java.awt.Dimension(661, 500));

        jlblMsj1_Agregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblMsj1_Agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMsj1_Agregar.setText("Agregar producto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rellenar campos"));
        jPanel1.setPreferredSize(new java.awt.Dimension(453, 551));

        jtfCodigo_Agregar.setEnabled(false);

        jtfPrecio_Agregar.setEnabled(false);

        jtfStock_Agregar.setToolTipText("");
        jtfStock_Agregar.setEnabled(false);

        jtfMarca_Agregar.setEnabled(false);

        jtfPies_Agregar.setEnabled(false);

        jcbCarga_Agregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "A", "C" }));
        jcbCarga_Agregar.setEnabled(false);

        jcbTipo_Agregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Jeans", "Cotele", "Tela" }));
        jcbTipo_Agregar.setEnabled(false);

        btnGroupSexo.add(jrbMasculino_Agregar);
        jrbMasculino_Agregar.setSelected(true);
        jrbMasculino_Agregar.setText("Hombre");
        jrbMasculino_Agregar.setEnabled(false);

        btnGroupSexo.add(jrbFemenino_Agregar);
        jrbFemenino_Agregar.setText("Mujer");
        jrbFemenino_Agregar.setEnabled(false);

        jbtnAgregar_Agregar.setText("Agregar");
        jbtnAgregar_Agregar.setEnabled(false);

        jbtnReset_Agregar.setText("Reset");
        jbtnReset_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReset_AgregarActionPerformed(evt);
            }
        });

        jlblCodigo_Agregar.setText("Codigo");

        jLabel4.setText("Precio");

        jLabel5.setText("Stock");

        jLabel6.setText("Marca");

        jLabel7.setText("Pies");

        jLabel8.setText("Carga");

        jLabel9.setText("Tipo");

        jLabel10.setText("Sexo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCodigo_Agregar)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfPrecio_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCodigo_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfStock_Agregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbTipo_Agregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfMarca_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfPies_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbCarga_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtnReset_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbMasculino_Agregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbFemenino_Agregar)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jbtnAgregar_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCodigo_Agregar)
                    .addComponent(jtfMarca_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPrecio_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jtfPies_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfStock_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jcbCarga_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipo_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMasculino_Agregar)
                    .addComponent(jrbFemenino_Agregar)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAgregar_Agregar)
                    .addComponent(jbtnReset_Agregar))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jcbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Pantalon", "Refrigerador", "Lavadora" }));
        jcbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProductoActionPerformed(evt);
            }
        });

        jlblMsj2_Agregar.setText("Seleccionar tipo");

        jlblImagePants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Trousers_52px.png"))); // NOI18N

        jlblImageWasher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Washing_Machine_52px.png"))); // NOI18N

        jlblImageFreezer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Fridge_52px.png"))); // NOI18N

        javax.swing.GroupLayout jpAgregarLayout = new javax.swing.GroupLayout(jpAgregar);
        jpAgregar.setLayout(jpAgregarLayout);
        jpAgregarLayout.setHorizontalGroup(
            jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarLayout.createSequentialGroup()
                .addGroup(jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblMsj2_Agregar)
                            .addComponent(jcbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAgregarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblImageWasher)
                            .addComponent(jlblImageFreezer)
                            .addComponent(jlblImagePants))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jpAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblMsj1_Agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAgregarLayout.setVerticalGroup(
            jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jlblMsj1_Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarLayout.createSequentialGroup()
                        .addComponent(jlblMsj2_Agregar)
                        .addGap(6, 6, 6)
                        .addComponent(jcbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jlblImageFreezer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblImagePants)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblImageWasher))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpParent.add(jpAgregar, "card2");

        jlblEliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblEliminarProducto.setText("Eliminar producto");

        jbtnEliminar_Eliminar.setText("Eliminar");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Search_Property_52px.png"))); // NOI18N

        javax.swing.GroupLayout jpEliminarLayout = new javax.swing.GroupLayout(jpEliminar);
        jpEliminar.setLayout(jpEliminarLayout);
        jpEliminarLayout.setHorizontalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblEliminarProducto)
                    .addGroup(jpEliminarLayout.createSequentialGroup()
                        .addComponent(jtfBuscar_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jbtnEliminar_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jlblNoExiste_Eliminar)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jpEliminarLayout.setVerticalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblEliminarProducto)
                .addGap(18, 18, 18)
                .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscar_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEliminar_Eliminar))
                .addGap(18, 18, 18)
                .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jlblNoExiste_Eliminar))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jpParent.add(jpEliminar, "card3");

        jlblListar_Listar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblListar_Listar.setText("Listar producto");

        jbtnListar_Listar.setText("Listar");
        jbtnListar_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListar_ListarActionPerformed(evt);
            }
        });

        jtaListar.setEditable(false);
        jtaListar.setColumns(20);
        jtaListar.setRows(5);
        jScrollPane1.setViewportView(jtaListar);

        javax.swing.GroupLayout jpListarLayout = new javax.swing.GroupLayout(jpListar);
        jpListar.setLayout(jpListarLayout);
        jpListarLayout.setHorizontalGroup(
            jpListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jpListarLayout.createSequentialGroup()
                        .addComponent(jlblListar_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(351, 351, 351)
                        .addComponent(jbtnListar_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        jpListarLayout.setVerticalGroup(
            jpListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListarLayout.createSequentialGroup()
                .addGroup(jpListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpListarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jbtnListar_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpListarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblListar_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jpParent.add(jpListar, "card4");

        getContentPane().add(jpParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 0, 620, -1));

        jMenuArchivo.setText("Archivo");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jmiSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuProcesos.setText("Procesos");

        jmiAgregar.setText("Agregar");
        jmiAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmiAgregar);

        jmiEliminar.setText("Eliminar");
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmiEliminar);

        jmiListar.setText("Listar");
        jmiListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jmiListar);

        jMenuBar1.add(jMenuProcesos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarActionPerformed
        jpParent.removeAll();
        jpParent.add(jpAgregar);
        jpParent.repaint();
        jpParent.revalidate();
        jpushEliminar.setBackground(new java.awt.Color(234, 234, 234));
        jpushListar.setBackground(new java.awt.Color(234, 234, 234));
        jPushAgregar.setBackground(new java.awt.Color(200, 220, 220));
    }//GEN-LAST:event_jmiAgregarActionPerformed

    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarActionPerformed
        jpParent.removeAll();
        jpParent.add(jpEliminar);
        jpParent.repaint();
        jpParent.revalidate();
        jpushEliminar.setBackground(new java.awt.Color(200, 220, 220));
        jpushListar.setBackground(new java.awt.Color(234, 234, 234));
        jPushAgregar.setBackground(new java.awt.Color(234, 234, 234));
    }//GEN-LAST:event_jmiEliminarActionPerformed

    private void jmiListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarActionPerformed
        jpParent.removeAll();
        jpParent.add(jpListar);
        jpParent.repaint();
        jpParent.revalidate();
        jpushEliminar.setBackground(new java.awt.Color(234, 234, 234));
        jpushListar.setBackground(new java.awt.Color(200, 220, 220));
        jPushAgregar.setBackground(new java.awt.Color(234, 234, 234));
    }//GEN-LAST:event_jmiListarActionPerformed

    private void jcbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProductoActionPerformed
        //Validaciones de interfaz
        if (this.jcbProducto.getSelectedIndex() == 0) {
            this.jbtnAgregar_Agregar.setEnabled(false);
            this.jtfMarca_Agregar.setEnabled(false);
            this.jtfPies_Agregar.setEnabled(false);
            this.jrbFemenino_Agregar.setEnabled(false);
            this.jrbMasculino_Agregar.setEnabled(false);
            this.jcbTipo_Agregar.setEnabled(false);
            this.jcbCarga_Agregar.setEnabled(false);
        }
        if (this.jcbProducto.getSelectedIndex() != 0) {
            this.jtfCodigo_Agregar.setEnabled(true);
            this.jtfPrecio_Agregar.setEnabled(true);
            this.jtfStock_Agregar.setEnabled(true);
            this.jlblImageFreezer.setVisible(false);
            this.jlblImageWasher.setVisible(false);
            this.jlblImagePants.setVisible(false);
        }
        else{
            this.jtfCodigo_Agregar.setEnabled(false);
            this.jtfPrecio_Agregar.setEnabled(false);
            this.jtfStock_Agregar.setEnabled(false);
        }
        
        if (this.jcbProducto.getSelectedIndex() == 1) {
            this.jbtnAgregar_Agregar.setEnabled(true);
            this.jtfMarca_Agregar.setEnabled(false);
            this.jtfPies_Agregar.setEnabled(false);
            this.jrbFemenino_Agregar.setEnabled(true);
            this.jrbMasculino_Agregar.setEnabled(true);
            this.jcbTipo_Agregar.setEnabled(true);
            this.jcbCarga_Agregar.setEnabled(false);
            this.jlblImagePants.setVisible(true);
            this.jlblImageWasher.setVisible(false);
            this.jlblImageFreezer.setVisible(false);
        }
        if (this.jcbProducto.getSelectedIndex() == 2) {
            this.jbtnAgregar_Agregar.setEnabled(true);
            this.jtfMarca_Agregar.setEnabled(true);
            this.jtfPies_Agregar.setEnabled(true);
            this.jrbFemenino_Agregar.setEnabled(false);
            this.jrbMasculino_Agregar.setEnabled(false);
            this.jcbTipo_Agregar.setEnabled(false);
            this.jcbCarga_Agregar.setEnabled(false);
            this.jlblImageFreezer.setVisible(true);
            this.jlblImageWasher.setVisible(false);
            this.jlblImagePants.setVisible(false);
        }
        if (this.jcbProducto.getSelectedIndex() == 3) {
            this.jbtnAgregar_Agregar.setEnabled(true);
            this.jtfMarca_Agregar.setEnabled(true);
            this.jtfPies_Agregar.setEnabled(false);
            this.jrbFemenino_Agregar.setEnabled(false);
            this.jrbMasculino_Agregar.setEnabled(false);
            this.jcbTipo_Agregar.setEnabled(false);
            this.jcbCarga_Agregar.setEnabled(true);
            this.jlblImageWasher.setVisible(true);
            this.jlblImagePants.setVisible(false);
            this.jlblImageFreezer.setVisible(false);
        }
    }//GEN-LAST:event_jcbProductoActionPerformed

    private void jbtnReset_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReset_AgregarActionPerformed
        this.jtfCodigo_Agregar.setText("");
        this.jtfPrecio_Agregar.setText("");
        this.jtfStock_Agregar.setText("");
        this.jtfMarca_Agregar.setText("");
        this.jtfPies_Agregar.setText("");
        this.jrbMasculino_Agregar.setSelected(true);
    }//GEN-LAST:event_jbtnReset_AgregarActionPerformed

    private void jbtnListar_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListar_ListarActionPerformed
        
    }//GEN-LAST:event_jbtnListar_ListarActionPerformed

    private void jPushAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPushAgregarMouseClicked
        jpParent.removeAll();
        jpParent.add(jpAgregar);
        jpParent.repaint();
        jpParent.revalidate();
        jpushEliminar.setBackground(new java.awt.Color(234, 234, 234));
        jpushListar.setBackground(new java.awt.Color(234, 234, 234));
        jPushAgregar.setBackground(new java.awt.Color(200, 220, 220));
    }//GEN-LAST:event_jPushAgregarMouseClicked

    private void jpushEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpushEliminarMouseClicked
        jpParent.removeAll();
        jpParent.add(jpEliminar);
        jpParent.repaint();
        jpParent.revalidate();
        jpushEliminar.setBackground(new java.awt.Color(200, 220, 220));
        jpushListar.setBackground(new java.awt.Color(234, 234, 234));
        jPushAgregar.setBackground(new java.awt.Color(234, 234, 234));
    }//GEN-LAST:event_jpushEliminarMouseClicked

    private void jpushListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpushListarMouseClicked
        jpParent.removeAll();
        jpParent.add(jpListar);
        jpParent.repaint();
        jpParent.revalidate();
        jpushEliminar.setBackground(new java.awt.Color(234, 234, 234));
        jpushListar.setBackground(new java.awt.Color(200, 220, 220));
        jPushAgregar.setBackground(new java.awt.Color(234, 234, 234));
    }//GEN-LAST:event_jpushListarMouseClicked

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuProcesos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPushAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAgregar_Agregar;
    public javax.swing.JButton jbtnEliminar_Eliminar;
    public javax.swing.JButton jbtnListar_Listar;
    public javax.swing.JButton jbtnReset_Agregar;
    public javax.swing.JComboBox<String> jcbCarga_Agregar;
    public javax.swing.JComboBox<String> jcbProducto;
    public javax.swing.JComboBox<String> jcbTipo_Agregar;
    private javax.swing.JLabel jlblCodigo_Agregar;
    private javax.swing.JLabel jlblEliminarProducto;
    private javax.swing.JLabel jlblImageFreezer;
    private javax.swing.JLabel jlblImagePants;
    private javax.swing.JLabel jlblImageWasher;
    private javax.swing.JLabel jlblListar_Listar;
    private javax.swing.JLabel jlblMsj1_Agregar;
    private javax.swing.JLabel jlblMsj2_Agregar;
    public javax.swing.JLabel jlblNoExiste_Eliminar;
    private javax.swing.JMenuItem jmiAgregar;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JMenuItem jmiListar;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JPanel jpAgregar;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpListar;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpParent;
    private javax.swing.JPanel jpushEliminar;
    private javax.swing.JPanel jpushListar;
    public javax.swing.JRadioButton jrbFemenino_Agregar;
    public javax.swing.JRadioButton jrbMasculino_Agregar;
    public javax.swing.JTextArea jtaListar;
    public javax.swing.JTextField jtfBuscar_Eliminar;
    public javax.swing.JTextField jtfCodigo_Agregar;
    public javax.swing.JTextField jtfMarca_Agregar;
    public javax.swing.JTextField jtfPies_Agregar;
    public javax.swing.JTextField jtfPrecio_Agregar;
    public javax.swing.JTextField jtfStock_Agregar;
    private javax.swing.JPanel panelAgregar;
    // End of variables declaration//GEN-END:variables
}
